services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - default
  
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --save 900 1 --save 300 10 --save 60 10000
    networks:
      - default
    volumes:
      - redis_data:/data

networks:
  default:
    driver: bridge

volumes:
  redis_data:
    driver: local